# Generated by Django 6.0.3 on 2026-07-03 19:20

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
            ],
            options={
                'verbose_name': 'برچسب طرف حساب',
                'verbose_name_plural': 'برچسب\u200cهای طرف حساب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('customer', 'مشتری'), ('supplier', 'تأمین\u200cکننده'), ('both', 'مشتری و تأمین\u200cکننده')], default='customer', max_length=10, verbose_name='نوع')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='شرکت/فروشگاه')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='موبایل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد/شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری سایت')),
                ('tags', models.ManyToManyField(blank=True, related_name='parties', to='parties.partytag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'طرف حساب',
                'verbose_name_plural': 'طرف حساب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار')], max_length=6, verbose_name='نوع')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('description', models.CharField(max_length=300, verbose_name='شرح')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شناسه سند')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع سند')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'سند دفتر حساب',
                'verbose_name_plural': 'اسناد دفتر حساب',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'دریافت از طرف حساب'), ('payment', 'پرداخت به طرف حساب')], max_length=7, verbose_name='نوع')),
                ('method', models.CharField(choices=[('cash', 'نقد'), ('card', 'کارت به کارت'), ('transfer', 'حواله بانکی'), ('cheque', 'چک'), ('other', 'سایر')], default='cash', max_length=10, verbose_name='روش')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='شرح')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('ledger_entry', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='parties.ledgerentry', verbose_name='سند دفتر')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'دریافت/پرداخت',
                'verbose_name_plural': 'دریافت\u200cها و پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['party', 'created_at'], name='parties_led_party_i_9bf1a0_idx'),
        ),
    ]
