# Generated by Django 6.0.3 on 2026-07-03 19:23

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا خودکار ساخته شود', max_length=20, null=True, unique=True, verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='آخرین قیمت خرید (ریال)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=5, verbose_name='نقطه سفارش مجدد'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='عدد', max_length=20, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت فروش (ریال)'),
        ),
    ]
