# Generated by Django 6.0.3 on 2026-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_code_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای نتایج گوگل. حداکثر ۱۶۰ کاراکتر.', max_length=160, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='خالی بماند تا از عنوان اصلی استفاده شود. حداکثر ۷۰ کاراکتر.', max_length=70, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای نتایج گوگل. حداکثر ۱۶۰ کاراکتر.', max_length=160, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='خالی بماند تا از عنوان اصلی استفاده شود. حداکثر ۷۰ کاراکتر.', max_length=70, verbose_name='عنوان سئو'),
        ),
    ]
