# Generated by Django 6.0.3 on 2026-07-03 18:53

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('status', 'تغییر وضعیت')], max_length=10, verbose_name='عملیات')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='شناسه رکورد')),
                ('object_repr', models.CharField(max_length=200, verbose_name='عنوان رکورد')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='تغییرات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع رکورد')),
            ],
            options={
                'verbose_name': 'رویداد حسابرسی',
                'verbose_name_plural': 'رویدادهای حسابرسی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='finance_aud_content_722a64_idx')],
            },
        ),
    ]
