# Generated by Django 6.0.3 on 2026-07-04 10:42

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('kind', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], default='expense', max_length=7, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته هزینه/درآمد',
                'verbose_name_plural': 'دسته\u200cهای هزینه/درآمد',
                'ordering': ['kind', 'name'],
                'unique_together': {('name', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], max_length=7, verbose_name='نوع')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='شرح')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.expensecategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'تراکنش هزینه/درآمد',
                'verbose_name_plural': 'هزینه\u200cها و درآمدها',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['kind', 'date'], name='finance_cas_kind_790b22_idx')],
            },
        ),
    ]
