# Generated by Django 6.0.3 on 2026-07-04 10:54

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensecategory_cashtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شد')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'یادآوری',
                'verbose_name_plural': 'یادآوری\u200cها',
                'ordering': ['date', 'id'],
            },
        ),
    ]
