# Generated by Django 6.0.3 on 2026-06-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='سازنده', max_length=100, verbose_name='نام سایت')),
                ('tagline', models.CharField(blank=True, default='فروشگاه تخصصی ابزار و مصالح ساختمانی', max_length=200, verbose_name='شعار')),
                ('about_text', models.TextField(blank=True, default='فروشگاه تخصصی ابزار و مصالح ساختمانی با بیش از ده سال سابقه در ارائه بهترین محصولات و خدمات با ضمانت کیفیت.', verbose_name='درباره ما (فوتر)')),
                ('phone', models.CharField(blank=True, default='۰۲۱-۱۲۳۴۵۶۷۸', max_length=30, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, default='info@sazandeh.ir', max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, default='تهران، خیابان ولیعصر', max_length=300, verbose_name='آدرس')),
                ('working_hours', models.CharField(blank=True, default='شنبه تا پنجشنبه، ۸ تا ۱۸', max_length=120, verbose_name='ساعت کاری')),
                ('shipping_note', models.CharField(blank=True, default='ارسال سریع به سراسر کشور', max_length=120, verbose_name='پیام ارسال (نوار بالا)')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.URLField(blank=True, verbose_name='واتساپ')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('copyright_text', models.CharField(blank=True, default='تمامی حقوق مادی و معنوی این وب\u200cسایت متعلق به فروشگاه سازنده می\u200cباشد.', max_length=300, verbose_name='متن کپی\u200cرایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
