# Generated by Django 6.0.3 on 2026-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(blank=True, default='تمامی حقوق مادی و معنوی این وب\u200cسایت متعلق به فروشگاه شن\u200cسازه می\u200cباشد.', max_length=300, verbose_name='متن کپی\u200cرایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='info@shensazeh.ir', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, default='09179100761', max_length=30, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='شن\u200cسازه', max_length=100, verbose_name='نام سایت'),
        ),
    ]
