# Generated by Django 6.0.3 on 2026-07-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_grant_staff_role_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='economic_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام رسمی فروشنده'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره ثبت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='نرخ پیش\u200cفرض مالیات بر ارزش افزوده (٪)'),
        ),
    ]
