# Generated by Django 6.0.3 on 2026-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_sitesetting_economic_code_sitesetting_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='invoice_sms_enabled',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک پس از صدور فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='invoice_sms_template',
            field=models.CharField(default='{name} عزیز، فاکتور {number} به مبلغ {amount} تومان صادر شد. {shop}', help_text='متغیرها: {name} {number} {amount} {due_date} {shop}', max_length=300, verbose_name='متن پیامک فاکتور'),
        ),
    ]
