# Generated by Django 6.0.3 on 2026-07-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_grant_visits_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Claude (Anthropic)'), ('openai', 'OpenAI')], default='anthropic', max_length=20, verbose_name='سرویس هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='کلید API کلاد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='anthropic_model',
            field=models.CharField(blank=True, default='claude-opus-5', max_length=60, verbose_name='مدل کلاد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='کلید API اوپن\u200cای\u200cآی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4o', max_length=60, verbose_name='مدل اوپن\u200cای\u200cآی'),
        ),
    ]
