# Generated by Django 6.0.3 on 2026-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_sitesetting_ai_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='openrouter_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='کلید API اوپن\u200cروتر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='openrouter_model',
            field=models.CharField(blank=True, default='anthropic/claude-opus-5', max_length=120, verbose_name='مدل اوپن\u200cروتر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='openrouter_web_search',
            field=models.BooleanField(default=False, help_text='مدل در صورت نیاز وب را جستجو می\u200cکند. حدود ۰.۰۰۵ دلار برای هر جستجو.', verbose_name='جستجوی وب هنگام تولید محتوا'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Claude (Anthropic)'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter (دسترسی به همه مدل\u200cها)')], default='anthropic', max_length=20, verbose_name='سرویس هوش مصنوعی'),
        ),
    ]
