# Generated by Django 6.0.3 on 2026-07-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_sitesetting_openrouter_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ai_proxy_url',
            field=models.CharField(blank=True, help_text='اختیاری. مثال: http://127.0.0.1:8118 — اگر سرویس، آی\u200cپی سرور را مسدود کرده باشد.', max_length=200, verbose_name='پراکسی برای سرویس\u200cهای هوش مصنوعی'),
        ),
    ]
