# Generated by Django 6.0.3 on 2026-07-04 10:48

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_backfill_invoice_parties'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.PositiveBigIntegerField(verbose_name='اصل مبلغ (ریال)')),
                ('method', models.CharField(choices=[('none', 'بدون سود'), ('simple', 'سود ساده سالانه'), ('reducing', 'سود بر مانده (اقساط مساوی)')], default='none', max_length=8, verbose_name='روش سود')),
                ('annual_rate', models.PositiveSmallIntegerField(default=0, verbose_name='نرخ سود سالانه (٪)')),
                ('count', models.PositiveSmallIntegerField(verbose_name='تعداد اقساط')),
                ('total_interest', models.PositiveBigIntegerField(default=0, verbose_name='جمع سود (ریال)')),
                ('total_payable', models.PositiveBigIntegerField(default=0, verbose_name='جمع قابل پرداخت (ریال)')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='سررسید قسط اول')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plan', to='orders.invoice', verbose_name='فاکتور')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'طرح اقساط',
                'verbose_name_plural': 'طرح\u200cهای اقساط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(verbose_name='شماره قسط')),
                ('due_date', django_jalali.db.models.jDateField(verbose_name='سررسید')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ قسط (ریال)')),
                ('paid_amount', models.PositiveBigIntegerField(default=0, verbose_name='پرداخت\u200cشده (ریال)')),
                ('paid_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='installments.installmentplan', verbose_name='طرح')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['plan', 'seq'],
                'indexes': [models.Index(fields=['due_date'], name='installment_due_dat_885b2a_idx')],
                'unique_together': {('plan', 'seq')},
            },
        ),
    ]
