# Generated by Django 6.0.3 on 2026-07-28 18:23

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='path',
            field=models.CharField(db_index=True, max_length=500, verbose_name='مسیر'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='visited_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ بازدید'),
        ),
    ]
