# Generated by Django 6.0.3 on 2026-03-31 18:15

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('in', 'ورود کالا'), ('out', 'خروج کالا')], max_length=3, verbose_name='نوع')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='تأمین\u200cکننده')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='orders.order', verbose_name='سفارش مرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ورودی/خروجی انبار',
                'verbose_name_plural': 'ورودی/خروجی\u200cهای انبار',
                'ordering': ['-created_at'],
            },
        ),
    ]
