# Generated by Django 6.0.3 on 2026-07-03 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('store', '0002_product_code_product_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'حرکت انبار', 'verbose_name_plural': 'حرکت\u200cهای انبار (کاردکس)'},
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='balance_after',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی پس از حرکت'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شناسه سند'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='unit_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد (ریال)'),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='entry_type',
            field=models.CharField(choices=[('in', 'ورود کالا'), ('out', 'خروج کالا'), ('return_in', 'برگشت به انبار'), ('return_out', 'برگشت از انبار'), ('adjust', 'اصلاح موجودی')], max_length=10, verbose_name='نوع'),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['product', 'created_at'], name='inventory_i_product_ae4891_idx'),
        ),
    ]
