# Generated by Django 6.0.3 on 2026-07-04 10:59

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کمپین')),
                ('message', models.TextField(help_text='متغیرها: {name} {mobile} {city}', verbose_name='متن پیام')),
                ('party_type', models.CharField(blank=True, help_text='خالی = همه', max_length=10, verbose_name='فیلتر نوع')),
                ('sent_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ارسال موفق')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.partytag', verbose_name='فیلتر برچسب')),
            ],
            options={
                'verbose_name': 'کمپین پیامکی',
                'verbose_name_plural': 'کمپین\u200cهای پیامکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('message', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق')], max_length=6, verbose_name='وضعیت')),
                ('provider', models.CharField(default='console', max_length=20, verbose_name='درگاه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.campaign', verbose_name='کمپین')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'پیامک ارسالی',
                'verbose_name_plural': 'پیامک\u200cهای ارسالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
