# Generated by Django 6.0.3 on 2026-03-31 18:15

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('message_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه پیام تلگرام')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پیام تلگرام',
                'verbose_name_plural': 'پیام\u200cهای تلگرام',
                'ordering': ['-created_at'],
            },
        ),
    ]
