# Generated by Django 6.0.3 on 2026-07-03 20:08

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_backfill_invoice_parties'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='بانک')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='شماره حساب')),
                ('serial_from', models.CharField(blank=True, max_length=30, verbose_name='سریال اول')),
                ('serial_to', models.CharField(blank=True, max_length=30, verbose_name='سریال آخر')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cچک',
                'verbose_name_plural': 'دسته\u200cچک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChequePrintLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, unique=True, verbose_name='بانک')),
                ('paper_width', models.PositiveSmallIntegerField(default=165, verbose_name='عرض چک (میلی\u200cمتر)')),
                ('paper_height', models.PositiveSmallIntegerField(default=80, verbose_name='ارتفاع چک (میلی\u200cمتر)')),
                ('date_x', models.PositiveSmallIntegerField(default=25, verbose_name='تاریخ — فاصله از راست')),
                ('date_y', models.PositiveSmallIntegerField(default=10, verbose_name='تاریخ — فاصله از بالا')),
                ('amount_x', models.PositiveSmallIntegerField(default=110, verbose_name='مبلغ عددی — فاصله از راست')),
                ('amount_y', models.PositiveSmallIntegerField(default=25, verbose_name='مبلغ عددی — فاصله از بالا')),
                ('words_x', models.PositiveSmallIntegerField(default=25, verbose_name='مبلغ حروفی — فاصله از راست')),
                ('words_y', models.PositiveSmallIntegerField(default=38, verbose_name='مبلغ حروفی — فاصله از بالا')),
                ('payee_x', models.PositiveSmallIntegerField(default=30, verbose_name='در وجه — فاصله از راست')),
                ('payee_y', models.PositiveSmallIntegerField(default=52, verbose_name='در وجه — فاصله از بالا')),
            ],
            options={
                'verbose_name': 'قالب چاپ چک',
                'verbose_name_plural': 'قالب\u200cهای چاپ چک',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('received', 'دریافتی'), ('issued', 'پرداختی')], max_length=8, verbose_name='نوع')),
                ('status', models.CharField(choices=[('pending', 'در جریان وصول'), ('cleared', 'وصول شده'), ('bounced', 'برگشت خورده')], default='pending', max_length=8, verbose_name='وضعیت')),
                ('serial', models.CharField(max_length=30, verbose_name='شماره چک')),
                ('sayad_id', models.CharField(blank=True, max_length=16, verbose_name='شناسه صیادی')),
                ('bank_name', models.CharField(max_length=100, verbose_name='بانک')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('due_date', django_jalali.db.models.jDateField(verbose_name='تاریخ سررسید')),
                ('payee', models.CharField(blank=True, max_length=200, verbose_name='در وجه')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='شرح')),
                ('status_changed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='orders.invoice', verbose_name='فاکتور مرتبط')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='parties.party', verbose_name='طرف حساب')),
                ('cheque_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='cheques.chequebook', verbose_name='دسته\u200cچک')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='cheques_che_status_2cc305_idx')],
            },
        ),
    ]
