# Generated by Django 6.0.3 on 2026-07-03 19:33

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('parties', '0001_initial'),
        ('store', '0002_product_code_product_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20, unique=True, verbose_name='نوع سند')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='پیشوند')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='شماره بعدی')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='طول عدد')),
            ],
            options={
                'verbose_name': 'سری شماره\u200cگذاری',
                'verbose_name_plural': 'سری\u200cهای شماره\u200cگذاری',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ابطال'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL, verbose_name='باطل\u200cکننده'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='doc_type',
            field=models.CharField(choices=[('sale', 'فاکتور فروش'), ('purchase', 'فاکتور خرید'), ('sale_return', 'برگشت از فروش'), ('purchase_return', 'برگشت از خرید'), ('proforma', 'پیش\u200cفاکتور')], default='sale', max_length=20, verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سررسید مانده'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ صدور'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف سطری (ریال)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداختی (ریال)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.party', verbose_name='طرف حساب'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='settlement_type',
            field=models.CharField(choices=[('cash', 'نقدی (تسویه کامل)'), ('partial', 'پرداخت جزئی'), ('credit', 'نسیه'), ('cheque', 'چک'), ('card', 'کارت به کارت'), ('installment', 'اقساطی')], default='cash', max_length=12, verbose_name='نحوه تسویه'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('cancelled', 'باطل شده')], default='draft', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submission_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='توکن ثبت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='نرخ مالیات (٪)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف سطر (ریال)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='واحد'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='خالی = نرخ فاکتور', null=True, verbose_name='نرخ مالیات سطر (٪)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف کلی (ریال)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تسویه شده'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='orders.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع اقلام (ریال)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات (ریال)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع کل (ریال)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت واحد (ریال)'),
        ),
    ]
